@echo off
echo Downloading the wget binaries...
echo Downloading the LlamaCPP binaries...
echo Downloading the Language model...
echo Downloading the Visual Encoder...
echo Unzipping the llama.cpp binaries...
echo Starting llama-server with 8192 tokens context window...
start cmd.exe /c llama-server.exe -m InternVL2_5-1B-Q8_0.gguf --mmproj mmproj-InternVL2_5-1B-Q8_0.gguf -ngl 0
echo Opening default browser in 10 seconds...
timeout /t 10
start http://localhost:8080